# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Tale
paginate:       5
baseurl:        ""
url:            "http://www.mrmarionette14.name"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         MrMarionette14
  url:          https://github.com/MrMarionette14
  email:        iforgetitagain@sina.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/MrMarionette14/mrmarionette14.github.io

# Gems
gems:
  - jekyll-paginate
