# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /blog/:year/:month/:day/:title.html
relative_permalinks: true

# Setup
title:               14's Blog
tagline:             'A blog based on jekyll'
description:         'As you see it's a personal blog.'
url:                 http://www.mrmarionette14.name
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              MrMarionette14
  url:               https://github.com/MrMarionette14
  email:             iforgetitagain@sina.com

# Custom vars
version:             1.0.0
