# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               14's Blog
tagline:             ''
description:         'As you see it's a personal blog.'
url:                 http://mrmarionette14.name
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              MrMarionette14
  url:               https://github.com/MrMarionette14
  email:             iforgetitagain@sina.com

# Custom vars
version:             1.0.0
